[project]
name = "tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bentoml>=1.4.22",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
pytorch-triton = { index = "pytorch-cu128" }
torch = { index = "pytorch-cu128" }
