version: "3.8"
services:
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
