[project]
name = "language-learning"
authors = [{ name = "Hiroaki Ogasawara" }]
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.4.1",
    "torchvision>=0.19.1",
    "tqdm>=4.66.5",
    "wandb>=0.18.0",
]
