exclude:
  - Dockerfile
  - environment.yml
  - Makefile
  - renovate.json5
  # Default
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
markdown_ext: "markdown,mkdown,mkdn,mkd,md,qmd"
