dit = "../models/framepack/dit/diffusion_pytorch_model-00001-of-00003.safetensors"
vae = "../models/framepack/vae/diffusion_pytorch_model.safetensors"
text_encoder1 = "../models/text_encoder/model-00001-of-00004.safetensors"
text_encoder2 = "../models/text_encoder_2/model.safetensors"
image_encoder = "../models/image_encoder/model.safetensors"
dataset_config = "dataset.toml"
sdpa = true
mixed_precision = "bf16"
fp8_base = true
optimizer_type = "adamw8bit"
learning_rate = 1e-4
gradient_checkpointing = true
max_data_loader_n_workers = 2
persistent_data_loader_workers = true
network_module = "networks.lora_framepack"
network_dim = 32
timestep_sampling = "shift"
discrete_flow_shift = 7.0
max_train_epochs = 16
save_every_n_epochs = 1
seed = 42
output_dir = "output"
output_name = "lora"
log_with = "wandb"
log_tracker_name = "fp-f1"
latent_window_size = 3
f1 = true
