[project]
name = "fp-f1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ascii-magic>=2.3.0",
    "huggingface-hub[cli]>=0.31.2",
    "jinja2-cli>=0.8.2",
    "matplotlib>=3.10.3",
    "tensorboard>=2.19.0",
]
