[project]
name = "module"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
module = "module:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
