[project]
name = "module"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "attrs>=25.3.0",
    "somepackage",
]

[project.scripts]
module = "module:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
somepackage = { path = "somepackage/dist/somepackage-0.1.0-py3-none-any.whl" }
