[project]
name = "extra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub[cli]>=0.29.3",
]

[dependency-groups]
dev = [
    "jinja2-cli>=0.8.2",
]
