#!/usr/bin/env sh

set -eu

NAME="www.2020games.metro.tokyo.lg.jp"
TYPE="A"

# echo "this is usually default server of dig to query. if macOS, this is not true."
# cat /etc/resolv.conf

echo "dig"
dig @8.8.8.8 +trace "$NAME" "$TYPE"

# if no server specified +trace option does not work as expected on my local environment.
# https://stackoverflow.com/questions/53688690/dig-trace-does-not-do-a-trace

echo "nslookup"
nslookup -type="$TYPE" "$NAME"
