[project]
name = "train-yolov8-on-custom-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ultralytics>=8.3.221",
]
