[project]
name = "get-started"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.4",
]

[dependency-groups]
dev = [
    "openmim>=0.3.9",
    "setuptools>=75.3.0",
]

[[tool.uv.index]]
url = "http://pypi.org/simple"
