AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    AwscliFunctionServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
          Version: "2012-10-17"
        ManagedPolicyArns:
          - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    AwscliLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        ContentUri: src/layer
        Description: Awscli runtime
    AwscliFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: src/function
        Handler: function.handler
        Role: !GetAtt AwscliFunctionServiceRole.Arn
        Runtime: provided
        Layers:
          - Ref: AwscliLayer
        MemorySize: 128
        Timeout: 300
      DependsOn:
        - AwscliFunctionServiceRole
