[project]
name = "http-sse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "httpx>=0.28.1",
    "mcp[cli]>=1.7.1",
    "starlette>=0.46.2",
    "uvicorn>=0.34.2",
]
