[tool.poetry]
name = "guidance_sandbox"
version = "0.1.0"
description = ""
authors = ["xhiroga <xhiroga@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "guidance_sandbox"}]

[tool.poetry.dependencies]
python = "3.9.12"
python-dotenv = "^1.0.0"
guidance = "^0.0.47"
numpy = "^1.24.3"   # [add numpy as dep · microsoft/guidance@19e5586](https://github.com/microsoft/guidance/commit/19e5586871a19f5fc91feb3b28e6c653963905f8)


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
flake8-bugbear = "^23.3.23"
mypy = "^1.2.0"
ipykernel = "^6.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
