[project]
name = "getting-started"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "omegaconf>=2.3.0",
]

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
warn_unused_ignores = true
