schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type Query {
  users: [User!]!
}

type Mutation {
  addUser(name: String!): User!
}

type Subscription {
  users: [User!]
}

type User {
  name: String
}
