[tool.poetry]
name = "langchain_sandbox"
version = "0.1.0"
description = ""
authors = ["xhiroga <13391129+xhiroga@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.12"
langchain = "^0.0.129"
openai = "^0.27.2"
python-dotenv = "^1.0.0"
google-search-results = "^2.4.2"
wikipedia = "^1.4.0"
chromadb = "^0.3.23"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
python-dotenv = {extras = ["cli"], version = "^1.0.0"}
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
flake8-bugbear = "^23.3.23"
mypy = "^1.2.0"
ipykernel = "^6.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
