[tool.poetry]
name = "lang-chain-agent-customized-by-llama-index-tool"
version = "0.1.0"
description = ""
authors = ["xhiroga <xhiroga@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "lang_chain_agent_customized_by_llama_index_tool"}]

[tool.poetry.dependencies]
python = "3.9.12"
openai = "^0.27.4"
llama-index = "^0.5.10"
langchain = "^0.0.135"
html2text = "^2020.1.16"


[tool.poetry.group.dev.dependencies]
python-dotenv = {extras = ["cli"], version = "^1.0.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
