AWSTemplateFormatVersion: 2010-09-09
Description: ECR TEST

Parameters:
  ENV:
    Type: String

Resources:
  til:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ENV}til-worker
      # ECRのリポジトリ名に大文字を使うことはできないので注意