AWSTemplateFormatVersion: 2010-09-09
Description: Configure AWS CloudTrail

Parameters:
  ManagedResourcePrefix:
    Type: "String"
    Description: "Prefix for the managed resources"

  EnableLogFileValidation:
    Type: String
    Default: "true"
    Description: Indicates whether CloudTrail validates the integrity of log files.
    AllowedValues:
      - "true"
      - "false"

  IncludeGlobalEvents:
    Type: String
    Default: "true"
    Description: Indicates whether the trail is publishing events from global services, such as IAM, to the log files.
    AllowedValues:
      - "true"
      - "false"

  MultiRegion:
    Type: String
    Default: "true"
    Description: Indicates whether the CloudTrail trail is created in the region in which you create the stack (false) or in all regions (true).
    AllowedValues:
      - "true"
      - "false"

  AllConfigTopicName:
    Type: String
    Default: ""
    Description: All Configuration Notification SNS Topic in Security Account that AWS Config delivers notifications to.

  SecurityAccountId:
    Type: "String"
    Description: AWS Account Id of the Security account.

  AuditBucketName:
    Type: String
    Default: ""
    Description: Audit Bucket name from the Log Archive Account

  PublishToCloudWatchLogs:
    Type: String
    Default: "true"
    Description: Indicates whether notifications are published to CloudWatch Logs.
    AllowedValues:
      - "true"
      - "false"

  LogsRetentionInDays:
    Description: "Specifies the number of days you want to retain CloudTrail log events in the CloudWatch Logs."
    Type: Number
    Default: 14
    AllowedValues:
      [
        1,
        3,
        5,
        7,
        14,
        30,
        60,
        90,
        120,
        150,
        180,
        365,
        400,
        545,
        731,
        1827,
        3653,
      ]

  AWSLogsS3KeyPrefix:
    Type: "String"
    Description: "Organization ID to use as the S3 Key prefix for storing the audit logs"

Conditions:
  IsMultiRegion: !Equals
    - !Ref MultiRegion
    - "true"

  IsPublishToCloudWatchLogs: !Equals
    - !Ref PublishToCloudWatchLogs
    - "true"

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Sub ${ManagedResourcePrefix}-BaselineCloudTrail
      S3BucketName: !Ref AuditBucketName
      S3KeyPrefix: !Ref AWSLogsS3KeyPrefix
      SnsTopicName: !Sub arn:aws:sns:${AWS::Region}:${SecurityAccountId}:${AllConfigTopicName}
      IsLogging: True
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !If
        - IsMultiRegion
        - True
        - !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion
      CloudWatchLogsLogGroupArn: !If
        - IsPublishToCloudWatchLogs
        - !GetAtt TrailLogGroup.Arn
        - !Ref AWS::NoValue
      CloudWatchLogsRoleArn: !If
        - IsPublishToCloudWatchLogs
        - !GetAtt TrailLogGroupRole.Arn
        - !Ref AWS::NoValue

  TrailLogGroup:
    Type: "AWS::Logs::LogGroup"
    Condition: IsPublishToCloudWatchLogs
    Properties:
      LogGroupName: !Sub ${ManagedResourcePrefix}/CloudTrailLogs
      RetentionInDays: !Ref LogsRetentionInDays

  TrailLogGroupRole:
    Type: "AWS::IAM::Role"
    Condition: IsPublishToCloudWatchLogs
    Properties:
      RoleName: !Sub ${ManagedResourcePrefix}-CloudWatchLogsRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CloudTrailAssumeRole
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "cloudtrail-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AWSCloudTrailCreateLogStream
                Effect: Allow
                Action: "logs:CreateLogStream"
                Resource: !GetAtt "TrailLogGroup.Arn"
              - Sid: AWSCloudTrailPutLogEvents
                Effect: Allow
                Action: "logs:PutLogEvents"
                Resource: !GetAtt "TrailLogGroup.Arn"

Outputs:
  BaselineCloudTrail:
    Description: Baseline CloudTrail
    Value: !GetAtt "Trail.Arn"
  CloudWatchLogsGroupArn:
    Description: CloudWatch Log Group ARN for Baseline CloudTrail
    Value: !GetAtt "TrailLogGroup.Arn"
  CloudWatchLogsGroupName:
    Description: CloudWatch Log Group Name for Baseline CloudTrail
    Value: !Ref TrailLogGroup
