[tool.poetry]
name = "overview"
version = "0.1.0"
description = ""
authors = ["xhiroga <13391129+xhiroga@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.4"
tensorflow-macos = "^2.10.0"
tensorflow-metal = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
