@startuml
(*) --> "マーケティング"
note right: キャンペーンを用いて見込み客を顧客化する
"マーケティング" --> "顧客化"
"顧客化" --> "営業"
note right: 契約を受注する(商談)
"営業" -->  "成約"
"成約" --> "カスタマーサポート"
note right: 問題解決にあたる(案件)
"カスタマーサポート" --> (*)
@enduml