#!/bin/sh

SSH_DIR=".ssh"
SSH_KEY="$SSH_DIR/id_ed25519"
SSH_KEY_PUB="$SSH_DIR/id_ed25519.pub"
AUTHORIZED_KEYS="$SSH_DIR/authorized_keys"

chmod 700 $SSH_DIR

ssh-keygen -t ed25519 -P "" -f "$SSH_KEY"
chmod 644 "$SSH_KEY_PUB"
chmod 600 "$SSH_KEY"

cat $SSH_KEY_PUB > "$AUTHORIZED_KEYS"
chmod 600 "$AUTHORIZED_KEYS"
