#!/usr/bin/env sh
# whatever sh executable appears first in the user $PATH

set -euxo pipefail
# set -e: stop script when one part of program fails.
# set -u: get an error when undefined value was referred.
# set -x: print out every command before it run.
# set -o pipefail: exit if one part of pipe fails.


### Reference
# https://jvns.ca/blog/2017/03/26/bash-quirks/
