AWSTemplateFormatVersion: 2010-09-09
Description: ECR TEST UPDATE

Parameters:
  ENV:
    Type: String

Resources:
  til:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ENV}til-worker