[project]
name = "av-hubert-visualizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "av-hubert-s2s",
    "gradio>=5.49.1",
    "plotly>=5.24.0",
    "umap-learn>=0.5.6",
]

[tool.uv.sources]
av-hubert-s2s = { git = "https://github.com/xhiroga/AV-HuBERT-S2S/" }
