[project]
name = "online-asr-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "sentencepiece>=0.2.1",
    "torch==2.8.0",
    "torchaudio>=2.8.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
pytorch-triton = { index = "pytorch-cu128" }
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }
