run: models/hubert_large_ll60k_finetune_ls960.pt
	uv run main.py

models/hubert_large_ll60k_finetune_ls960.pt:
	curl -L -o $@ https://dl.fbaipublicfiles.com/hubert/hubert_large_ll60k_finetune_ls960.pt
