[project]
name = "hubert"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "editdistance>=0.8.1",
    "fairseq>=0.12.2",
    "hydra-core==1.0.7",
    "numpy<1.24",
    "opencv-python>=4.8.1.78",
    "python-speech-features>=0.6",
    "scipy>=1.15.3",
    "sentencepiece>=0.2.1",
    "tensorboardx>=2.6.4",
]

[project.optional-dependencies]
demo = [
    "dlib>=20.0.0",
    "ipykernel>=6.30.1",
    "pickleshare>=0.7.5",
    "scikit-image>=0.24.0",
    "scikit-video>=1.1.11",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
fairseq = { git = "https://github.com/facebookresearch/fairseq.git", rev = "v0.12.2" }
