AWSTemplateFormatVersion: 2010-09-09
Description: Configure an Audit S3 bucket for the Log Archive account.

Parameters:
  SSEAlgorithm:
    Type: "String"
    Default: "AES256"
    Description: S3 bucket SSE Algorithm.
    AllowedValues:
      - "AES256"
      - "aws:kms"
  KMSMasterKeyID:
    Type: "String"
    Description: "KMS key ID required if SSE algorithm is aws:kms."
  ManagedResourcePrefix:
    Type: "String"
    Description: "Prefix for the managed resources"
  RetentionDays:
    Type: String
    Description: "No of Days to retain the logs, after which it will be permanently deleted"
  TransitionToGlacier:
    Type: String
    Description: "Do you wish to transition the logs to Glacier before permanently deleting?"
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"
  TransitionDays:
    Type: String
    Description: "No of Days to transition the data from S3 to Glacier"
  AWSLogsS3KeyPrefix:
    Type: "String"
    Description: "Organization ID to use as the S3 Key prefix for storing the audit logs"

Conditions:
  UseKMS: !Equals
    - !Ref SSEAlgorithm
    - "aws:kms"
  MoveToGlacier: !Equals
    - !Ref TransitionToGlacier
    - "Yes"

Resources:
  # Create S3 Server Access Logging bucket
  S3LoggingBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ManagedResourcePrefix}-s3-access-logs-${AWS::AccountId}-${AWS::Region}
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - !If
            - UseKMS
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: !Ref SSEAlgorithm
                KMSMasterKeyID: !Ref KMSMasterKeyID
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: !Ref SSEAlgorithm
  # Create S3 Audit bucket
  S3AuditBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ManagedResourcePrefix}-logs-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LoggingBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - !If
            - UseKMS
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: !Ref SSEAlgorithm
                KMSMasterKeyID: !Ref KMSMasterKeyID
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: !Ref SSEAlgorithm
      LifecycleConfiguration:
        Rules:
          - !If
            - MoveToGlacier
            - Id: RetentionRule
              Status: Enabled
              ExpirationInDays: !Ref RetentionDays
              NoncurrentVersionExpirationInDays: !Ref RetentionDays
              Transitions:
                - TransitionInDays: !Ref TransitionDays
                  StorageClass: Glacier
              NoncurrentVersionTransitions:
                - TransitionInDays: !Ref TransitionDays
                  StorageClass: Glacier
            - Id: RetentionRule
              Status: Enabled
              ExpirationInDays: !Ref RetentionDays
              NoncurrentVersionExpirationInDays: !Ref RetentionDays
  # Create Bucket Policy for S3 Audit bucket
  S3AuditBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3AuditBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
                - config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:aws:s3:::${S3AuditBucket}"
          - Sid: AWSBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
                - config.amazonaws.com
            Action: s3:PutObject
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - !Ref "S3AuditBucket"
                    - !Sub "/${AWSLogsS3KeyPrefix}/AWSLogs/*/*"

Outputs:
  BucketName:
    Description: Audit S3 bucket name
    Value: !Ref S3AuditBucket
  LoggingBucketName:
    Description: S3 Access Logging Bucket name
    Value: !Ref S3LoggingBucket
  AuditLogsS3KeyPrefix:
    Description: S3 Key prefix for storing the audit logs
    Value: !Ref AWSLogsS3KeyPrefix
