[project]
name = "rendezvous"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyzmq>=26.4.0",
    "requests>=2.31.0",
]

[dependency-groups]
dev = [
    "types-requests>=2.32.0.20250328",
]
