#!/bin/sh
aws ce get-cost-and-usage \
--time-period Start=$(gdate -d '-1 month' '+%Y-%m')-01,End=$(gdate '+%Y-%m')-01 \
--granularity MONTHLY \
--metrics BlendedCost \
--group-by Type=DIMENSION,Key=SERVICE Type=DIMENSION,Key=LINKED_ACCOUNT\
| jq -r '.ResultsByTime[].Groups[] | [(.Keys[]), .Metrics.BlendedCost.Amount] | @csv'
