[project]
name = "wan2-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.14",
    "av>=14.2.0",
    "comfyui-frontend-package>=1.15.0",
    "einops>=0.8.1",
    "kornia>=0.8.0",
    "numpy>=2.2.4",
    "pillow>=11.1.0",
    "psutil>=7.0.0",
    "pyyaml>=6.0.2",
    "safetensors>=0.5.3",
    "scipy>=1.15.2",
    "sentencepiece>=0.2.0",
    "spandrel>=0.4.1",
    "tokenizers>=0.21.1",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchsde>=0.2.6",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
    "transformers>=4.50.0",
    "yarl>=1.18.3",
]

[dependency-groups]
dev = [
    "huggingface-hub[cli]>=0.29.3",
    "nvitop>=1.4.2",
]

[tool.uv]
# WSL や LambdaLabs は hardlink に対応していない。
link-mode = "symlink"

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126"}
