## Deployment
apiVersion: apps/v1
kind: StatefulSet

metadata:
  namespace: monitoring
  labels:
    zabbix-app: zabbix-server
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      zabbix-app: zabbix-server
  serviceName: "zabbix-server"
  #strategy:
  #  type: Recreate
  template:
    metadata:
      labels:
        zabbix-app: zabbix-server
    spec:
      containers:
        - image: zabbix/zabbix-server-mysql:ubuntu-4.4-latest
          name: zabbix-server
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: zabbix-app

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 10051
      restartPolicy: Always

#### Service
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    zabbix-app: zabbix-server
  name: zabbix-server
spec:
  ports:
    - name: "10051"
      port: 10051
      targetPort: 10051
  selector:
    zabbix-app: zabbix-server
status:
  loadBalancer: {}
