[tool.poetry]
name = "babyagi-sandbox"
version = "0.1.0"
description = ""
authors = ["xhiroga <xhiroga@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "babyagi_sandbox"}]

[tool.poetry.dependencies]
python = "^3.11"
argparse = "1.4.0"
openai = "0.27.4"
pinecone-client = "2.2.1"
pre-commit = ">=3.2.0"
python-dotenv = "1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
