[project]
name = "kijai-wanvideo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "huggingface-hub[cli]>=0.29.3",
    "nvitop>=1.4.2",
]
